<div class="jumbotron">
    <h1>Welcome to <span class="zf-green">ZF3.Prototype.Project</span></h1>

    <p>
        Congratulations! You can download orginal skeleton here      
        <a href="https://github.com/zendframework/ZendSkeletonApplication" target="_blank">ZF Skeleton Application</a>.
        You are currently running Zend Framework version <?= \Application\Module::VERSION ?>.
        This skeleton can serve as a simple starting point for you to begin
        building your application on ZF.
    </p>

    <p><a class="btn btn-success btn-lg" href="https://github.com/krolpiotr/zfskeleton" target="_blank">Download ZF3.Prototype.Project from GitHub &raquo;</a></p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">About me</h3>
            </div>
            <div class="panel-body">
                <p>
                    My name is Piotr Krol. 
                    My website <a href="http://simon-phoenix.se" target="_blank">simon-phoenix.se</a>, 
                    My GitHub <a href="https://github.com/krolpiotr/" target="_blank">github.com/krolpiotr</a>, 
                </p>

                <p><a class="btn btn-success pull-right" href="http://simon-phoenix.se" target="_blank">simon-phoenix.se &raquo;</a></p>
            </div>
        </div>
    </div>




    

  
    
</div>
